import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Spline from "@splinetool/react-spline/next";
import ToggleVisibility from "../components/ToggleVisibility"; // Import ToggleVisibility

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <ToggleVisibility>{children}</ToggleVisibility>

        <Spline
          scene="https://prod.spline.design/HHjgfeq41C7BcECT/scene.splinecode"
          className="absolute top-0 left-0 w-full h-full border-none -z-10"
        />
        <Spline
          scene="https://prod.spline.design/5reZgj-W45KzNdra/scene.splinecode"
          className="absolute top-0 right-0 h-full border-none -z-10"
        />
      </body>
    </html>
  );
}
